name: kaosmos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.81114
title: "kaosmos' grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0000'
    - '#ffffff'
    - '#d94040'
    - '#efb0b0'
    - '#e68080'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
