layout_spectrum: 0.2189348704014711
typography_spectrum: 0.7118831729257276
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.23309635789622324
  lightness: 0.5630116314174479
  saturation: 0.30495481208695263
  rhythmicContrast: 0.7991305670909362
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Matteo Nicoletti
  email: matteo@kaosmos.it
  url: 'https://thegrid.ai/kaosmos'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2644bef8-c459-4486-8bc2-08a7e6eeae8a.svg
name: kaosmos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about.me
    url: 'https://about.me/matteo.nicoletti'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3cfd56be-8748-4c9f-bcbb-a2388d33a621.svg
title: kaosmos
content: []
description: kaosmos placeholder
purpose: []
