typography_spectrum: 0.16034803842194378
color:
  brandColors:
    - '#B8BFB7'
    - '#90A199'
    - '#62967F'
    - '#054D41'
    - '#556F6C'
  brandStrength: 0.17097348417155445
  lightness: 0.502214768435806
  saturation: 0.9388478810433298
  rhythmicContrast: 0.47337024426087737
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.713987217284739
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Matteo Nicoletti
  email: matteo@kaosmos.it
  url: 'https://thegrid.ai/kaosmos/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd145802-8ef6-4d57-9131-c3e80554b919.png
name: kaosmos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: my web site
    url: 'http://kaosmos.it'
    type: external
  - name: my Tumblr
    url: 'http://tumblr.kaosmos.it/'
    type: external
  - name: Home page
    id: 55c2df17-76bb-4d0c-bfe8-fe8095d52e02
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/69f66cef-b54b-4659-9542-faa2d4a4421b.png
title: il domatore di div
description: >-
  web design, fotografia, sperimentazioni e altri accidenti. sopratutto altri
  accidenti.
purpose: []
