typography_spectrum: 0.74586
color:
  brandColors:
    - '#cc0000'
    - '#ffffff'
    - '#d94040'
    - '#efb0b0'
    - '#e68080'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: kaosmos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: il domatore di div
description: >-
  Web design, photography, tinkering and other mishaps. Especially other
  mishaps.
purpose: []
