name: kaosmos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.81114
title: "kaosmos' grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0c08'
    - '#878e98'
    - '#4c4034'
    - '#a6a9ae'
    - '#e2e0e5'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.9521388933062553
purpose: []
