typography_spectrum: 0.74586
color:
  brandColors:
    - '#cc0000'
    - '#ffffff'
    - '#d94040'
    - '#efb0b0'
    - '#e68080'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Matteo Nicoletti
  email: matteo@kaosmos.it
  url: 'https://thegrid.ai/kaosmos/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd145802-8ef6-4d57-9131-c3e80554b919.png
name: kaosmos
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/69f66cef-b54b-4659-9542-faa2d4a4421b.png
title: il domatore di div
description: >-
  Web design, fotografia, sperimentazioni e altri accidenti. Sopratutto altri
  accidenti.
purpose: []
